### ISSUE TITLE
앱이 다운됩니다.

### ISSUE THREAD

**Issue by NakGun** [bootpay/flutter#1]
에러메시지
E/AndroidRuntime(12190): Process: onedrive.live.connecting, PID: 12190
E/AndroidRuntime(12190): java.lang.RuntimeException: Unable to start activity ComponentInfo{onedrive.live.connecting/kr.co.bootpay.bootpay_api.BootpayActivity}: java.lang.IllegalStateException: PG.KCP is not classified

제가 수행한 내역입니다.
1. 회원가입
2. 결제수단 kcp / 카드결제 / 테스트모드
3. 인증키 : 안드로이드(5eb9555a02f57e00291ee2f5) /플러터로 애뮬레이터로 테스트

**Comment by ehowlsla** [comment]
pg: 'PG.KCP' 가 아니라
string 형태인 'kcp' 로 해주시면 감사하겠습니다

**Comment by NakGun** [comment]
아 감사합니다 바로 해결되었습니다.^^
빠른 피드백 정말 고맙습니다.
부트페이 홈페이지를 보고 따라했었는데 플러터 플러그인 예제 내용이 정확하네요
업데이트 해주시면 좋을거 같습니다~!
