### ISSUE TITLE
web 지원이 안됩니다.

### ISSUE THREAD

**Issue by cholnh** [bootpay/flutter#2]
1.0.9 버전 사용 중, WEB 에서는 해당 모듈이 진행되지 않습니다.

WEB 지원 계획이 있으신가요?

**flutter doctor -v**

[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [Version 10.0.18362.836], locale ko-KR)
    • Flutter version 1.17.0 at C:\Dev\flutter_windows_v1.12.13+hotfix.5-stable\flutter
    • Framework revision e6b34c2b5c (5 weeks ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc3)
    • Android SDK at C:\Users\choln\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.0-rc3
    • ANDROID_HOME = C:\Users\choln\AppData\Local\Android\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Ultimate Edition (version 2019.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA 2018.3.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[√] Connected device (3 available)
    • SHV E330S  • c02d49a3   • android-arm    • Android 5.0.1 (API 21)
    • Chrome     • chrome     • web-javascript • Google Chrome 83.0.4103.97
    • Web Server • web-server • web-javascript • Flutter Tools

! Doctor found issues in 1 category.

**Comment by ehowlsla** [comment]
지원할 수 있도록 노력해보겠습니다.
