### ISSUE TITLE
부트페이 response의 action값에 대해 문의드립니다.

### ISSUE THREAD

**Issue by s2s2kim** [bootpay/flutter#3]
안녕하세요 부트페이를 연동해서 서비스 개발중인데요
카드 결제시 ISP/페이북과 같이 다른 앱으로 실제 결제를 랜더링 하는 경우
해당 앱에서 결제를 취소하는 경우
부트페이에서 action 값을 "BootpayError"로
response를 내려주는데요 이 경우에는 BootpayCancel로 내려와져야하지 않을까 싶은데요
혹시 이 부분에 대해 어떻게 생각하시는지 여쭤봐도 될까요?

**Comment by ehowlsla** [comment]
넵 말씀주신 부분이 맞습니다.
확인해보고 cancel로 갈 수 있도록 업데이트 하겠습니다.

**Comment by s2s2kim** [comment]
@ehowlsla 
넵 빠르게 답장주셔서 너무 감사드립니다! ^^

**Comment by ehowlsla** [comment]
확인해보니 PG사에서 cancel_url이 아닌 error_url 로 리턴해주고 있어서, 부트페이 또한 그대로 전달하다보니 그렇게 응답되고 있습니다. 이에 대해 예외처리하기가 케이스가 다양하여 쉽지않다보니 부득이하게 저렇게 안내되는 점 양해부탁드립니다.
